all:
	@echo "Do even more nothing"

build:
	@echo "" >/dev/null

install:
	@echo "" >/dev/null

clean:
	@echo "" >/dev/null

syntax:
	@for i in `find ./ -type f -name "*.rb"`; do \
			echo -en "Checking $$i: "; \
			ruby -c $$i; \
	done
